<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas [
    <!ELEMENT personas (persona)+>
    <!ELEMENT persona (nombre,apellido1,apellido2,email?,telefono_movil?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido1 (#PCDATA)>
    <!ELEMENT apellido2 (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT telefono_movil (#PCDATA)>
]>
<personas>
        <persona>
            <nombre>Carmen</nombre>
            <apellido1>López</apellido1>
            <apellido2>López</apellido2>
            <email>carmen@gmail.com</email>
            <telefono_movil>600100100</telefono_movil>
        </persona>
        <persona>
            <nombre>Carla</nombre>
            <apellido1>Díez</apellido1>
            <apellido2>Matecón</apellido2>
            <email>carlad@gmail.com</email>
        </persona>
        <persona>
            <nombre>Miren</nombre>
            <apellido1>Gaztañaga</apellido1>
            <apellido2>Aramburu</apellido2>
            <telefono_movil>700200200</telefono_movil>
        </persona>
</personas>