=== FoxyGamer1156/Ceinmark/LM/XSD/Ejer_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- Elementos simples definidos por el usuario -->
        <xs:simpleType name="medidas">
            <xs:restriction base="xs:postiveinteger">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType name="patron1">
            <xs:restriction base="xs:string">
                <xs:minLength value="3"/>
                <xs:maxLength value="50"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType name="vacio">
            <xs:restriction base="xs:string">
                <xs:length value="0"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType name="patron_id">
            <xs:restriction base="xs:string">
                <xs:pattern value="[X-Z]{2}[0-9]{4}"/>
            </xs:restriction>
        </xs:simpleType>


    <!-- Elementos simples -->
    <xs:element name="tamano" type="medidas"/>
    <xs:element name="color">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="#([A-F]|[0-9]){6}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="descripcion">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="10"/>
                <xs:maxLength value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="titulo" type="patron1"/>
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="(([aA-zZ]|[0-9])+)\@(([aA-zZ]|[0-9])+).es"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-ZÁÉÍÓÚ]{1,2}[a-záéíóúü]{1,}((\s|-)[A-ZÁÉÍÓÚ]{1,2}[a-záéíóúü]{1,})*"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="id" type="patron_id"/>
    <xs:element name="subtitulo_canal" type="patron1"/>
    <xs:element name="titulo_canal" type="patron"/>


    <!-- Atributos -->
    <xs:attribute name="altura" type="medidas"/>
    <xs:attribute name="anchura" type="medidas"/>
    <xs:attribute name="referencia" type="anyURI"/>
    <xs:attribute name="id" type="patron_id"/>
    <xs:attribute name="href" type="anyURI"/>


    <!-- Elementos compuestos por el usuario -->


    <!-- Elementos compuestos -->
    <xs:element name="imagen">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension>
                    <xs:attribute ref="altura"/>
                    <xs:attribute ref="anchura"/>
                </xs:extension>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[aA-zZ]+(.jpg|.png)"/>
                </xs:restriction>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="enlace">
        <xs:complexType>
            <xs:attribute ref="referencia"/>
        </xs:complexType>
    </xs:element>
    <xs:element>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tamano"/>
                <xs:element ref="color"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="noticia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="enlace"/>
                <xs:element ref="imagen"/>
                <xs:element ref="visualizar" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="descripcion"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="director">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="email"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="link">
        <xs:complexType>
            <xs:attribute ref="href"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="canal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo_canal"/>
                <xs:element ref="subtitulo_canal"/>
                <xs:element ref="link"/>
                <xs:element ref="director"/>
                <xs:element ref="noticia" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FoxyGamer1156/Ceinmark/LM/XML/Ejercicios/Ejer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE canal[
    <!ELEMENT canal (titulo_canal, subtitulo_canal, link, director, id, noticia+)>
    <!ELEMENT director (nombre,email)>
    <!ELEMENT noticia (titulo,enlace,imagen,visualizar?,descripcion)>
    <!ELEMENT visualizar (tamano,color)>
    <!ELEMENT titulo_canal (#PCDATA)>
    <!ELEMENT subtitulo_canal (#PCDATA)>
    <!ELEMENT link EMPTY>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT enlace (#PCDATA)>
    <!ELEMENT imagen (#PCDATA)>
    <!ELEMENT tamano (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ATTLIST noticia id ID #REQUIRED>
    <!ATTLIST link href CDATA #REQUIRED>
    <!ATTLIST enlace referencia CDATA #REQUIRED>
    <!ATTLIST imagen altura CDATA #IMPLIED>
    <!ATTLIST imagen anchura CDATA #IMPLIED>
]>-->
<!--<canal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd2.xsd"> -->
<canal xmlns:xsi="http://www.w3.org/2001/XMLSchema:positiveinteger" xsi:noNamespaceSchemaLocation="../../XSD/Ejer_XSD.xsd">
          <titulo_canal>TITULO_CANAL</titulo_canal>
          <subtitulo_canal>SUBTITULO_CANAL</subtitulo_canal>
          <link href="http://www.example.org"/>
          <director>
                    <nombre>Juan Antonio</nombre>
                    <email>lopezquesada@iessanjuanbosco.es</email>
          </director>
          <id>XY2356</id>
          <noticia id="XY2589">
                    <titulo>TITULO_NOTICIA1</titulo>
                    <enlace referencia="http://www.example.org/2011/12/13/noticia1"/>
                    <imagen altura="100" anchura="25">img12.jpg</imagen>
                    <visualizar>
                              <tamano>12</tamano>
                              <color>#FF2233</color>
                    </visualizar>
                    <descripcion>DESC_NOTICIA1</descripcion>
          </noticia>
          <noticia id="XY2548">
                    <titulo>TITULO_NOTICIA2</titulo>
                    <enlace referencia="http://www.example.org/2011/12/13/noticia2"/>
                    <imagen>img158.jpg</imagen>
                    <descripcion>TITULO_NOTICIA2</descripcion>
          </noticia>
</canal>
