=== FoxyGamer1156/Ceinmark/LM/XSD/Examen-1404.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- Elementos simples definidos por el usuario -->
    <xs:simpleType name="formato_titulo_subtitulo_descripcion">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z_0-9]{3,}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="formato_nombre">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-ZÁÉÍÓÚ]{1,2}[a-záéíóúü]{1,}((\s|-)[A-ZÁÉÍÓÚ]{1,2}[a-záéíóúü]{1,})*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="vacios">
        <xs:restriction base="xs:string">
            <xs:length value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="formato_color">
        <xs:restriction base="xs:string">
            <xs:pattern value="#(([0-9]|[A-F]){2}){3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="formato_noticia_id">
        <xs:restriction base="xs:string">
            <xs:pattern value="X-Z]{2}[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="formato_email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="formato_imagen">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z-a-z-0-9]+(.)((jpg)|(png)|(webp))"/>
        </xs:restriction>
    </xs:simpleType>
<!-- Elementos simples -->
<xs:element name="descripcion" type="formato_titulo_subtitulo_descripcion"/>

<xs:element name="color" type="formato_color"/>

<xs:element name="tamanno" type="xs:positiveInteger"/>

<xs:element name="titulo" type="formato_titulo_subtitulo_descripcion"/>

<xs:element name="nombre" type="formato_nombre"/>

<xs:element name="subtitulo_canal" type="formato_titulo_subtitulo_descripcion"/>

<xs:element name="titulo_canal" type="formato_titulo_subtitulo_descripcion"/>
<!-- Atributos -->
<xs:attribute name="href" type="xs:anyURI"/>

<xs:attribute name="id" type="formato_noticia_id"/>

<xs:attribute name="rederencia" type="xs:anyURI"/>

<xs:attribute name="altura" type="xs:positiveInteger"/>

<xs:attribute name="anchura" type="xs:positiveInteger"/>

<!-- Elementos compuestos por el usuario -->
<xs:element name="link">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="vacio">
                <xs:attribute ref="href" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="enlace">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="vacio">
                <xs:attribute ref="referencia" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>
<xs:element name="imagen">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base ="formato_imagen">
                <xs:attribute ref="altura" use="optional"/>
                <xs:attribute ref="anchura" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<!-- Elementos compuestos -->
<xs:element name="visualizar">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="tamanno"/>
            <xs:element ref="color"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="noticia">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="titulo"/>
            <xs:element ref="enlace"/>
            <xs:element ref="imagen"/>
            <xs:element ref="visualizar" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="descripcion"/>
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="director">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="email"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="canal">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="titulo_canal"/>
            <xs:element ref="subtitulo_canal"/>
            <xs:element ref="link"/>
            <xs:element ref="director"/>
            <xs:element ref="id"/>
            <xs:element ref="noticia" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== FoxyGamer1156/Ceinmark/LM/XML/Examen-1404.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE canal [
  <!ELEMENT canal (titulo_canal,subtitulo_canal,link,director,id,noticia+)>
  <!ELEMENT director (nombre, email)>
  <!ELEMENT noticia (titulo, enlace, imagen, visualizar?, descripcion)>
  <!ELEMENT visualizar (tamanno, color)>
  
  <!ELEMENT titulo_canal (#PCDATA)>
  <!ELEMENT subtitulo_canal (#PCDATA)>
  <!ELEMENT link EMPTY>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT enlace EMPTY>
  <!ELEMENT imagen (#PCDATA)>
  <!ELEMENT tamanno (#PCDATA)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  
  <!ATTLIST link href CDATA #REQUIRED>
  <!ATTLIST noticia id ID #REQUIRED>
  <!ATTLIST enlace referencia CDATA #REQUIRED>
  <!ATTLIST imagen altura CDATA #IMPLIED
                                     anchura CDATA #IMPLIED>
]>-->
<canal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Examen-1404.xsd">
          <titulo_canal>TITULO_CANAL</titulo_canal>
          <subtitulo_canal>SUBTITULO_CANAL</subtitulo_canal>
          <link href="http://www.example.org"/>
          <director>
                    <nombre>Juan Antonio</nombre>
                    <email>lopezquesada@iessanjuanbosco.es</email>
          </director>
          <id>XY2356</id>
          <noticia id="XY2589">
                    <titulo>TITULO_NOTICIA1</titulo>
                    <enlace referencia="http://www.example.org/2011/12/13/noticia1"/>
                    <imagen altura="100" anchura="25">img12.jpg</imagen>
                    <visualizar>
                              <tamanno>12</tamanno>
                              <color>#FF2233</color>
                    </visualizar>
                    <descripcion>DESC_NOTICIA1</descripcion>
          </noticia>
          <noticia id="XY2548">
                    <titulo>TITULO_NOTICIA2</titulo>
                    <enlace referencia="http://www.example.org/2011/12/13/noticia2"/>
                    <imagen>img158.jpg</imagen>
                    <descripcion>TITULO_NOTICIA2</descripcion>
          </noticia>
</canal>
